<?php


echo '<header style="'
echo 'filter: drop-shadow(0px 0px 8px #185eb7);">'
echo '    <a class="logo" href=""><img src="img/BANER_TRANS_FERRIS.png" alt="logo"></a>'
echo '    <nav>'
echo '        <ul class="nav__links">'
echo '            <li class="dropdown">'
echo '                <a href="#">Информация</a>'
echo '                <div class="dropdown-content">'
echo '                    <a href="..">Главная</a>'
echo '                    <a href="faq">Частые вопросы</a>'
echo '                    <a href="rules">Правила</a>'
echo '                    <a href="law">Законы</a>'
echo '                    <a href="commands">Команды</a>'
echo '                    <a href="updates">Обновления</a>'
echo '                </div>'
echo '            </li>'
echo ''
echo '            <li class="dropdown">'
echo '                <a href="#">Игра</a>'
echo '                <div class="dropdown-content">'
echo '                    <a href="imgs">Картинки</a>'
echo '                    <a href="create_item">Предметы</a>'
echo '                    <a href="trading.php">Трейды</a>'
echo '                </div>'
echo '            </li>'
echo ''
echo ''
echo '            <li class="dropdown">'
echo '                <a id="resource_pack_version" href="#">Ресур-пак 1.1</a>'
echo '                <div class="dropdown-content">'
echo '                    <a href="files/EmpireProjektPack.zip">Полная версия</a>'
echo '                    <a href="files/EmpireProjektPack_Light.zip">Легкая версия(без звуков)</a>'
echo '                </div>'
echo '            </li>'
echo '            <li><a href="donate">Донат</a></li>'
echo '            <li><a href="https://discord.gg/Gwukdr8">Дискорд</a></li>'
echo '            <li><a href="https://vk.com/empireprojekt">ВК</a></li>'
echo '        </ul>'
echo '    </nav>'
echo '</header>'
?>